# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisualRecognition.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1374, 1096)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 0, 321, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 100, 321, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 10, 20, 161))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 170, 331, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(330, 10, 20, 161))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(18, 198, 81, 16))
        self.label_9.setObjectName("label_9")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(8, 178, 331, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(-2, 188, 20, 291))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(10, 480, 331, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(330, 190, 20, 291))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 300, 79))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnObjectPath = QtWidgets.QPushButton(self.layoutWidget)
        self.btnObjectPath.setObjectName("btnObjectPath")
        self.horizontalLayout.addWidget(self.btnObjectPath)
        self.pathToObject = QtWidgets.QLineEdit(self.layoutWidget)
        self.pathToObject.setObjectName("pathToObject")
        self.horizontalLayout.addWidget(self.pathToObject)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnScenePath = QtWidgets.QPushButton(self.layoutWidget)
        self.btnScenePath.setObjectName("btnScenePath")
        self.horizontalLayout_2.addWidget(self.btnScenePath)
        self.pathToScene = QtWidgets.QLineEdit(self.layoutWidget)
        self.pathToScene.setObjectName("pathToScene")
        self.horizontalLayout_2.addWidget(self.pathToScene)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(520, 10, 20, 561))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(880, 10, 20, 561))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(1220, 10, 20, 561))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_27 = QtWidgets.QFrame(self.centralwidget)
        self.line_27.setGeometry(QtCore.QRect(530, 560, 701, 21))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.btnShowTransformImg = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowTransformImg.setGeometry(QtCore.QRect(900, 450, 196, 23))
        self.btnShowTransformImg.setObjectName("btnShowTransformImg")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(544, 418, 55, 16))
        self.label_35.setObjectName("label_35")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(900, 10, 318, 427))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line_20 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_7.addWidget(self.line_20)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_7.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_7.addWidget(self.label_37)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.kf_colorCorrection = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.kf_colorCorrection.setSingleStep(0.1)
        self.kf_colorCorrection.setProperty("value", 1.0)
        self.kf_colorCorrection.setObjectName("kf_colorCorrection")
        self.horizontalLayout_30.addWidget(self.kf_colorCorrection)
        self.en_colorCorrection = QtWidgets.QCheckBox(self.layoutWidget1)
        self.en_colorCorrection.setObjectName("en_colorCorrection")
        self.horizontalLayout_30.addWidget(self.en_colorCorrection)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_30.addWidget(self.label_38)
        self.verticalLayout_7.addLayout(self.horizontalLayout_30)
        self.line_21 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_7.addWidget(self.line_21)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_7.addWidget(self.label_39)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.kf_contrastCorrection = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.kf_contrastCorrection.setSingleStep(0.1)
        self.kf_contrastCorrection.setProperty("value", 1.0)
        self.kf_contrastCorrection.setObjectName("kf_contrastCorrection")
        self.horizontalLayout_32.addWidget(self.kf_contrastCorrection)
        self.en_contrastCorrection = QtWidgets.QCheckBox(self.layoutWidget1)
        self.en_contrastCorrection.setObjectName("en_contrastCorrection")
        self.horizontalLayout_32.addWidget(self.en_contrastCorrection)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_32.addWidget(self.label_40)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        self.line_22 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.verticalLayout_7.addWidget(self.line_22)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_7.addWidget(self.label_41)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.kf_brightnessCorrection = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.kf_brightnessCorrection.setSingleStep(0.1)
        self.kf_brightnessCorrection.setProperty("value", 1.0)
        self.kf_brightnessCorrection.setObjectName("kf_brightnessCorrection")
        self.horizontalLayout_31.addWidget(self.kf_brightnessCorrection)
        self.en_brightCorrection = QtWidgets.QCheckBox(self.layoutWidget1)
        self.en_brightCorrection.setObjectName("en_brightCorrection")
        self.horizontalLayout_31.addWidget(self.en_brightCorrection)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_31.addWidget(self.label_42)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        self.line_23 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.verticalLayout_7.addWidget(self.line_23)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_7.addWidget(self.label_43)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.kf_sharpnessCorrection = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.kf_sharpnessCorrection.setSingleStep(0.1)
        self.kf_sharpnessCorrection.setProperty("value", 1.0)
        self.kf_sharpnessCorrection.setObjectName("kf_sharpnessCorrection")
        self.horizontalLayout_33.addWidget(self.kf_sharpnessCorrection)
        self.en_sharpCorrection = QtWidgets.QCheckBox(self.layoutWidget1)
        self.en_sharpCorrection.setObjectName("en_sharpCorrection")
        self.horizontalLayout_33.addWidget(self.en_sharpCorrection)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_33.addWidget(self.label_44)
        self.verticalLayout_7.addLayout(self.horizontalLayout_33)
        self.line_24 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.verticalLayout_7.addWidget(self.line_24)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_7.addWidget(self.label_45)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_19.addWidget(self.label_46)
        self.gauss_kernell1 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.gauss_kernell1.setProperty("value", 1)
        self.gauss_kernell1.setObjectName("gauss_kernell1")
        self.verticalLayout_19.addWidget(self.gauss_kernell1)
        self.horizontalLayout_34.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_47 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_20.addWidget(self.label_47)
        self.gauss_kernell2 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.gauss_kernell2.setProperty("value", 1)
        self.gauss_kernell2.setObjectName("gauss_kernell2")
        self.verticalLayout_20.addWidget(self.gauss_kernell2)
        self.horizontalLayout_34.addLayout(self.verticalLayout_20)
        self.en_blurCorrection = QtWidgets.QCheckBox(self.layoutWidget1)
        self.en_blurCorrection.setObjectName("en_blurCorrection")
        self.horizontalLayout_34.addWidget(self.en_blurCorrection)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        self.line_25 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.verticalLayout_7.addWidget(self.line_25)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(541, 11, 342, 548))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.line_13 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_12.addWidget(self.line_13)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.absX = QtWidgets.QLineEdit(self.layoutWidget2)
        self.absX.setObjectName("absX")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.absX)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_13)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.absY = QtWidgets.QLineEdit(self.layoutWidget2)
        self.absY.setObjectName("absY")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.absY)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_16)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.absCh = QtWidgets.QLineEdit(self.layoutWidget2)
        self.absCh.setObjectName("absCh")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.absCh)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.verticalLayout_6.addLayout(self.formLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.line_16 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_12.addWidget(self.line_16)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_12.addWidget(self.label_19)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_9.addWidget(self.label_20)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.firstX = QtWidgets.QSpinBox(self.layoutWidget2)
        self.firstX.setMaximum(10000)
        self.firstX.setObjectName("firstX")
        self.horizontalLayout_10.addWidget(self.firstX)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_10.addWidget(self.label_21)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.firstY = QtWidgets.QSpinBox(self.layoutWidget2)
        self.firstY.setMaximum(10000)
        self.firstY.setObjectName("firstY")
        self.horizontalLayout_11.addWidget(self.firstY)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.secondX = QtWidgets.QSpinBox(self.layoutWidget2)
        self.secondX.setMaximum(10000)
        self.secondX.setObjectName("secondX")
        self.horizontalLayout_12.addWidget(self.secondX)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.secondY = QtWidgets.QSpinBox(self.layoutWidget2)
        self.secondY.setMaximum(10000)
        self.secondY.setObjectName("secondY")
        self.horizontalLayout_13.addWidget(self.secondY)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_13.addWidget(self.label_24)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.thirdX = QtWidgets.QSpinBox(self.layoutWidget2)
        self.thirdX.setMaximum(10000)
        self.thirdX.setObjectName("thirdX")
        self.horizontalLayout_14.addWidget(self.thirdX)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_14.addWidget(self.label_25)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.thirdY = QtWidgets.QSpinBox(self.layoutWidget2)
        self.thirdY.setMaximum(10000)
        self.thirdY.setObjectName("thirdY")
        self.horizontalLayout_15.addWidget(self.thirdY)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_15)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_28.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.sh_firstX = QtWidgets.QSpinBox(self.layoutWidget2)
        self.sh_firstX.setMaximum(10000)
        self.sh_firstX.setObjectName("sh_firstX")
        self.horizontalLayout_20.addWidget(self.sh_firstX)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_20.addWidget(self.label_28)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.sh_firstY = QtWidgets.QSpinBox(self.layoutWidget2)
        self.sh_firstY.setMaximum(10000)
        self.sh_firstY.setObjectName("sh_firstY")
        self.horizontalLayout_21.addWidget(self.sh_firstY)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_21.addWidget(self.label_29)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_21)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.sh_secondX = QtWidgets.QSpinBox(self.layoutWidget2)
        self.sh_secondX.setMaximum(10000)
        self.sh_secondX.setObjectName("sh_secondX")
        self.horizontalLayout_23.addWidget(self.sh_secondX)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_23.addWidget(self.label_30)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.sh_secondY = QtWidgets.QSpinBox(self.layoutWidget2)
        self.sh_secondY.setMaximum(10000)
        self.sh_secondY.setObjectName("sh_secondY")
        self.horizontalLayout_24.addWidget(self.sh_secondY)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_24.addWidget(self.label_31)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_24)
        self.verticalLayout_11.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.sh_thirdX = QtWidgets.QSpinBox(self.layoutWidget2)
        self.sh_thirdX.setMaximum(10000)
        self.sh_thirdX.setObjectName("sh_thirdX")
        self.horizontalLayout_26.addWidget(self.sh_thirdX)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_26.addWidget(self.label_32)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.sh_thirdY = QtWidgets.QSpinBox(self.layoutWidget2)
        self.sh_thirdY.setMaximum(10000)
        self.sh_thirdY.setObjectName("sh_thirdY")
        self.horizontalLayout_27.addWidget(self.sh_thirdY)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_27.addWidget(self.label_33)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_27)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.horizontalLayout_28.addLayout(self.verticalLayout_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_28)
        self.en_affine = QtWidgets.QCheckBox(self.layoutWidget2)
        self.en_affine.setObjectName("en_affine")
        self.verticalLayout_12.addWidget(self.en_affine)
        self.line_18 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_12.addWidget(self.line_18)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_14.addWidget(self.label_34)
        self.resized_scale = QtWidgets.QSlider(self.layoutWidget2)
        self.resized_scale.setMinimum(1)
        self.resized_scale.setMaximum(100)
        self.resized_scale.setProperty("value", 1)
        self.resized_scale.setSliderPosition(1)
        self.resized_scale.setOrientation(QtCore.Qt.Horizontal)
        self.resized_scale.setObjectName("resized_scale")
        self.verticalLayout_14.addWidget(self.resized_scale)
        self.resized_progress = QtWidgets.QProgressBar(self.layoutWidget2)
        self.resized_progress.setMinimum(1)
        self.resized_progress.setProperty("value", 2)
        self.resized_progress.setObjectName("resized_progress")
        self.verticalLayout_14.addWidget(self.resized_progress)
        self.en_resized = QtWidgets.QCheckBox(self.layoutWidget2)
        self.en_resized.setObjectName("en_resized")
        self.verticalLayout_14.addWidget(self.en_resized)
        self.verticalLayout_12.addLayout(self.verticalLayout_14)
        self.line_19 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_12.addWidget(self.line_19)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.rotation_scale = QtWidgets.QDial(self.layoutWidget2)
        self.rotation_scale.setMaximum(360)
        self.rotation_scale.setSliderPosition(0)
        self.rotation_scale.setOrientation(QtCore.Qt.Horizontal)
        self.rotation_scale.setInvertedControls(False)
        self.rotation_scale.setWrapping(True)
        self.rotation_scale.setNotchTarget(15.0)
        self.rotation_scale.setNotchesVisible(True)
        self.rotation_scale.setObjectName("rotation_scale")
        self.horizontalLayout_29.addWidget(self.rotation_scale)
        self.rotation_progress = QtWidgets.QLCDNumber(self.layoutWidget2)
        self.rotation_progress.setObjectName("rotation_progress")
        self.horizontalLayout_29.addWidget(self.rotation_progress)
        self.verticalLayout_12.addLayout(self.horizontalLayout_29)
        self.en_rotation = QtWidgets.QCheckBox(self.layoutWidget2)
        self.en_rotation.setObjectName("en_rotation")
        self.verticalLayout_12.addWidget(self.en_rotation)
        self.line_26 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.verticalLayout_12.addWidget(self.line_26)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(150, 110, 20, 61))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_28 = QtWidgets.QFrame(self.centralwidget)
        self.line_28.setGeometry(QtCore.QRect(10, 210, 331, 16))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 110, 308, 54))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.line_29 = QtWidgets.QFrame(self.centralwidget)
        self.line_29.setGeometry(QtCore.QRect(332, 502, 20, 481))
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(20, 510, 91, 16))
        self.label_49.setObjectName("label_49")
        self.line_30 = QtWidgets.QFrame(self.centralwidget)
        self.line_30.setGeometry(QtCore.QRect(0, 500, 20, 481))
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.line_31 = QtWidgets.QFrame(self.centralwidget)
        self.line_31.setGeometry(QtCore.QRect(12, 522, 331, 16))
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.line_32 = QtWidgets.QFrame(self.centralwidget)
        self.line_32.setGeometry(QtCore.QRect(10, 620, 331, 16))
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.line_33 = QtWidgets.QFrame(self.centralwidget)
        self.line_33.setGeometry(QtCore.QRect(10, 490, 331, 16))
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.line_35 = QtWidgets.QFrame(self.centralwidget)
        self.line_35.setGeometry(QtCore.QRect(10, 980, 331, 16))
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.line_34 = QtWidgets.QFrame(self.centralwidget)
        self.line_34.setGeometry(QtCore.QRect(10, 820, 331, 16))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 630, 217, 193))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_56 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_13.addWidget(self.label_56)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.HessianTresholdSurf = QtWidgets.QSpinBox(self.layoutWidget4)
        self.HessianTresholdSurf.setMinimum(100)
        self.HessianTresholdSurf.setMaximum(10000)
        self.HessianTresholdSurf.setProperty("value", 300)
        self.HessianTresholdSurf.setObjectName("HessianTresholdSurf")
        self.horizontalLayout_38.addWidget(self.HessianTresholdSurf)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_38.addWidget(self.label_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.nmOctave = QtWidgets.QSpinBox(self.layoutWidget4)
        self.nmOctave.setMinimum(1)
        self.nmOctave.setProperty("value", 4)
        self.nmOctave.setObjectName("nmOctave")
        self.horizontalLayout_39.addWidget(self.nmOctave)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_39.addWidget(self.label_5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.nmOctaveLayers = QtWidgets.QSpinBox(self.layoutWidget4)
        self.nmOctaveLayers.setMinimum(1)
        self.nmOctaveLayers.setMaximum(100)
        self.nmOctaveLayers.setProperty("value", 2)
        self.nmOctaveLayers.setObjectName("nmOctaveLayers")
        self.horizontalLayout_40.addWidget(self.nmOctaveLayers)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_40.addWidget(self.label_8)
        self.verticalLayout_13.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.DescriptorSize = QtWidgets.QSpinBox(self.layoutWidget4)
        self.DescriptorSize.setMaximum(1)
        self.DescriptorSize.setProperty("value", 1)
        self.DescriptorSize.setObjectName("DescriptorSize")
        self.horizontalLayout_41.addWidget(self.DescriptorSize)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_41.addWidget(self.label_55)
        self.verticalLayout_13.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.mesureKeyPointSurf = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.mesureKeyPointSurf.setMinimum(0.01)
        self.mesureKeyPointSurf.setMaximum(0.99)
        self.mesureKeyPointSurf.setSingleStep(0.01)
        self.mesureKeyPointSurf.setProperty("value", 0.75)
        self.mesureKeyPointSurf.setObjectName("mesureKeyPointSurf")
        self.horizontalLayout_9.addWidget(self.mesureKeyPointSurf)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_9.addWidget(self.label_51)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(350, 740, 20, 241))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(730, 740, 20, 241))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_36 = QtWidgets.QFrame(self.centralwidget)
        self.line_36.setGeometry(QtCore.QRect(360, 970, 381, 31))
        self.line_36.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.line_37 = QtWidgets.QFrame(self.centralwidget)
        self.line_37.setGeometry(QtCore.QRect(360, 720, 381, 31))
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 540, 212, 78))
        self.widget.setObjectName("widget")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnMesureSurfImg = QtWidgets.QPushButton(self.widget)
        self.btnMesureSurfImg.setObjectName("btnMesureSurfImg")
        self.verticalLayout_5.addWidget(self.btnMesureSurfImg)
        self.btnShowRecognitionSurf = QtWidgets.QPushButton(self.widget)
        self.btnShowRecognitionSurf.setObjectName("btnShowRecognitionSurf")
        self.verticalLayout_5.addWidget(self.btnShowRecognitionSurf)
        self.horizontalLayout_46.addLayout(self.verticalLayout_5)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_50 = QtWidgets.QLabel(self.widget)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_21.addWidget(self.label_50)
        self.btnSaveSurf = QtWidgets.QPushButton(self.widget)
        self.btnSaveSurf.setObjectName("btnSaveSurf")
        self.verticalLayout_21.addWidget(self.btnSaveSurf)
        self.horizontalLayout_46.addLayout(self.verticalLayout_21)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 830, 307, 145))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_57 = QtWidgets.QLabel(self.widget1)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_15.addWidget(self.label_57)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.numberKp1_Surf = QtWidgets.QLineEdit(self.widget1)
        self.numberKp1_Surf.setObjectName("numberKp1_Surf")
        self.horizontalLayout_35.addWidget(self.numberKp1_Surf)
        self.label_52 = QtWidgets.QLabel(self.widget1)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_35.addWidget(self.label_52)
        self.verticalLayout_15.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.numberKp2_Surf = QtWidgets.QLineEdit(self.widget1)
        self.numberKp2_Surf.setObjectName("numberKp2_Surf")
        self.horizontalLayout_36.addWidget(self.numberKp2_Surf)
        self.label_53 = QtWidgets.QLabel(self.widget1)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_36.addWidget(self.label_53)
        self.verticalLayout_15.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.goodMatchesSurf = QtWidgets.QLineEdit(self.widget1)
        self.goodMatchesSurf.setObjectName("goodMatchesSurf")
        self.horizontalLayout_45.addWidget(self.goodMatchesSurf)
        self.label_63 = QtWidgets.QLabel(self.widget1)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_45.addWidget(self.label_63)
        self.verticalLayout_15.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.numberGood_Surf = QtWidgets.QLineEdit(self.widget1)
        self.numberGood_Surf.setObjectName("numberGood_Surf")
        self.horizontalLayout_37.addWidget(self.numberGood_Surf)
        self.label_54 = QtWidgets.QLabel(self.widget1)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_37.addWidget(self.label_54)
        self.verticalLayout_15.addLayout(self.horizontalLayout_37)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(10, 230, 212, 78))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnMesureImg = QtWidgets.QPushButton(self.widget2)
        self.btnMesureImg.setObjectName("btnMesureImg")
        self.verticalLayout_4.addWidget(self.btnMesureImg)
        self.btnShowRecognitionSift = QtWidgets.QPushButton(self.widget2)
        self.btnShowRecognitionSift.setObjectName("btnShowRecognitionSift")
        self.verticalLayout_4.addWidget(self.btnShowRecognitionSift)
        self.horizontalLayout_47.addLayout(self.verticalLayout_4)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_12 = QtWidgets.QLabel(self.widget2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_22.addWidget(self.label_12)
        self.btnSaveSift = QtWidgets.QPushButton(self.widget2)
        self.btnSaveSift.setObjectName("btnSaveSift")
        self.verticalLayout_22.addWidget(self.btnSaveSift)
        self.horizontalLayout_47.addLayout(self.verticalLayout_22)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(10, 310, 307, 173))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mesureKeyPoint = QtWidgets.QDoubleSpinBox(self.widget3)
        self.mesureKeyPoint.setMinimum(0.01)
        self.mesureKeyPoint.setMaximum(0.99)
        self.mesureKeyPoint.setSingleStep(0.01)
        self.mesureKeyPoint.setProperty("value", 0.75)
        self.mesureKeyPoint.setObjectName("mesureKeyPoint")
        self.horizontalLayout_3.addWidget(self.mesureKeyPoint)
        self.label_14 = QtWidgets.QLabel(self.widget3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.numberKp1 = QtWidgets.QLineEdit(self.widget3)
        self.numberKp1.setObjectName("numberKp1")
        self.horizontalLayout_4.addWidget(self.numberKp1)
        self.label_11 = QtWidgets.QLabel(self.widget3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.numberKp2 = QtWidgets.QLineEdit(self.widget3)
        self.numberKp2.setObjectName("numberKp2")
        self.horizontalLayout_5.addWidget(self.numberKp2)
        self.label_48 = QtWidgets.QLabel(self.widget3)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_5.addWidget(self.label_48)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.numberGood = QtWidgets.QLineEdit(self.widget3)
        self.numberGood.setObjectName("numberGood")
        self.horizontalLayout_6.addWidget(self.numberGood)
        self.label_10 = QtWidgets.QLabel(self.widget3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.goodMatchesSift = QtWidgets.QLineEdit(self.widget3)
        self.goodMatchesSift.setObjectName("goodMatchesSift")
        self.horizontalLayout_48.addWidget(self.goodMatchesSift)
        self.label_64 = QtWidgets.QLabel(self.widget3)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_48.addWidget(self.label_64)
        self.verticalLayout_3.addLayout(self.horizontalLayout_48)
        self.widget4 = QtWidgets.QWidget(self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(370, 741, 320, 234))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_58 = QtWidgets.QLabel(self.widget4)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_23.addWidget(self.label_58)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.btnMessureCorrelation = QtWidgets.QPushButton(self.widget4)
        self.btnMessureCorrelation.setObjectName("btnMessureCorrelation")
        self.verticalLayout_16.addWidget(self.btnMessureCorrelation)
        self.btnShowRecognitionCorrelation = QtWidgets.QPushButton(self.widget4)
        self.btnShowRecognitionCorrelation.setObjectName("btnShowRecognitionCorrelation")
        self.verticalLayout_16.addWidget(self.btnShowRecognitionCorrelation)
        self.horizontalLayout_42.addLayout(self.verticalLayout_16)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_59 = QtWidgets.QLabel(self.widget4)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_18.addWidget(self.label_59)
        self.horizontalLayout_42.addLayout(self.verticalLayout_18)
        self.verticalLayout_23.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.correlationType = QtWidgets.QSpinBox(self.widget4)
        self.correlationType.setMinimum(1)
        self.correlationType.setMaximum(5)
        self.correlationType.setSingleStep(2)
        self.correlationType.setObjectName("correlationType")
        self.horizontalLayout_44.addWidget(self.correlationType)
        self.label_61 = QtWidgets.QLabel(self.widget4)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_44.addWidget(self.label_61)
        self.verticalLayout_23.addLayout(self.horizontalLayout_44)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_62 = QtWidgets.QLabel(self.widget4)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_17.addWidget(self.label_62)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.correlationKf = QtWidgets.QLineEdit(self.widget4)
        self.correlationKf.setObjectName("correlationKf")
        self.horizontalLayout_43.addWidget(self.correlationKf)
        self.label_60 = QtWidgets.QLabel(self.widget4)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_43.addWidget(self.label_60)
        self.verticalLayout_17.addLayout(self.horizontalLayout_43)
        self.verticalLayout_23.addLayout(self.verticalLayout_17)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1374, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "SIFT - алгоритм:"))
        self.label_3.setText(_translate("MainWindow", "Пути к файлам для сравнения:"))
        self.btnObjectPath.setText(_translate("MainWindow", "Обзор"))
        self.pathToObject.setText(_translate("MainWindow", "None..."))
        self.label.setText(_translate("MainWindow", "Путь к объету"))
        self.btnScenePath.setText(_translate("MainWindow", "Обзор"))
        self.pathToScene.setText(_translate("MainWindow", "None..."))
        self.label_2.setText(_translate("MainWindow", "Путь к сцене:"))
        self.btnShowTransformImg.setText(_translate("MainWindow", "Вывести обработанное изображение"))
        self.label_35.setText(_translate("MainWindow", "Вращение:"))
        self.label_36.setText(_translate("MainWindow", "Модуль яркостных преобразований\n"
"для изображения объекта"))
        self.label_37.setText(_translate("MainWindow", "Цветокоррекция:"))
        self.en_colorCorrection.setText(_translate("MainWindow", ":Подключить цветокоррекцию"))
        self.label_38.setText(_translate("MainWindow", "Примечание:\n"
"0 - ч/б\n"
"1 - исходное"))
        self.label_39.setText(_translate("MainWindow", "Контраст:"))
        self.en_contrastCorrection.setText(_translate("MainWindow", ":Подключить контраст"))
        self.label_40.setText(_translate("MainWindow", "Примечание:\n"
"0 - серое\n"
"1 - исходное"))
        self.label_41.setText(_translate("MainWindow", "Яркость:"))
        self.en_brightCorrection.setText(_translate("MainWindow", ":Подключить яркость"))
        self.label_42.setText(_translate("MainWindow", "Примечание:\n"
"0 - черное\n"
"1 - исходное"))
        self.label_43.setText(_translate("MainWindow", "Резкость:"))
        self.en_sharpCorrection.setText(_translate("MainWindow", ":Подключить резкость"))
        self.label_44.setText(_translate("MainWindow", "Примечание:\n"
"0 - размытое\n"
"1 - исходное\n"
"2 - заостренное"))
        self.label_45.setText(_translate("MainWindow", "Размытие по Гауссу:"))
        self.label_46.setText(_translate("MainWindow", "Ядро 1:"))
        self.label_47.setText(_translate("MainWindow", "Ядро 2:"))
        self.en_blurCorrection.setText(_translate("MainWindow", ":Подключить размытие"))
        self.label_15.setText(_translate("MainWindow", "Модуль геометрических преобразований\n"
" для изображения объекта"))
        self.absX.setText(_translate("MainWindow", "None..."))
        self.label_13.setText(_translate("MainWindow", " :X"))
        self.absY.setText(_translate("MainWindow", "None..."))
        self.label_16.setText(_translate("MainWindow", " :Y"))
        self.absCh.setText(_translate("MainWindow", "None..."))
        self.label_17.setText(_translate("MainWindow", ":Ch"))
        self.label_18.setText(_translate("MainWindow", "Размеры изображения:\n"
"Ширина (Х)\n"
"Высота (Y)\n"
"Каналы(Ch)"))
        self.label_19.setText(_translate("MainWindow", "Аффиное преобразование:"))
        self.label_20.setText(_translate("MainWindow", "Координаты точек:"))
        self.label_21.setText(_translate("MainWindow", "X1"))
        self.label_22.setText(_translate("MainWindow", "Y1"))
        self.label_23.setText(_translate("MainWindow", "X2"))
        self.label_24.setText(_translate("MainWindow", "Y2"))
        self.label_25.setText(_translate("MainWindow", "X3"))
        self.label_26.setText(_translate("MainWindow", "Y3"))
        self.label_27.setText(_translate("MainWindow", "Координаты смещения точек:"))
        self.label_28.setText(_translate("MainWindow", "X1"))
        self.label_29.setText(_translate("MainWindow", "Y1"))
        self.label_30.setText(_translate("MainWindow", "X2"))
        self.label_31.setText(_translate("MainWindow", "Y2"))
        self.label_32.setText(_translate("MainWindow", "X3"))
        self.label_33.setText(_translate("MainWindow", "Y3"))
        self.en_affine.setText(_translate("MainWindow", ":Подключить афииные преобразования"))
        self.label_34.setText(_translate("MainWindow", "Масштабирование (процент от оригинала):"))
        self.en_resized.setText(_translate("MainWindow", ":Подключить масштабирование"))
        self.en_rotation.setText(_translate("MainWindow", ":Подключить вращение"))
        self.label_6.setText(_translate("MainWindow", "Примечание:\n"
"Путь к файлу указывается \n"
"только с использованием \n"
"английских символов"))
        self.label_7.setText(_translate("MainWindow", "Сравнение двух изображений:\n"
"объект - снятое изображение\n"
"сцена - эталонное изображение"))
        self.label_49.setText(_translate("MainWindow", "SURF - алгоритм:"))
        self.label_56.setText(_translate("MainWindow", "Настройка детектора:"))
        self.label_4.setText(_translate("MainWindow", ": Порог детектора"))
        self.label_5.setText(_translate("MainWindow", ": Количество Октав"))
        self.label_8.setText(_translate("MainWindow", ": Количество уровней в Октаве"))
        self.label_55.setText(_translate("MainWindow", ": Размер дескриптора\n"
"  0 - 64 элемента\n"
"  1 - 128 элементов"))
        self.label_51.setText(_translate("MainWindow", "Коэффициент сравнения\n"
"дескрипторов\n"
"от 0 до 1"))
        self.btnMesureSurfImg.setText(_translate("MainWindow", "Сравнить\n"
"изображения"))
        self.btnShowRecognitionSurf.setText(_translate("MainWindow", "Вывести\n"
"изображения"))
        self.label_50.setText(_translate("MainWindow", "Примечание:\n"
"сначала идет сравнение\n"
"затем индикация"))
        self.btnSaveSurf.setText(_translate("MainWindow", "Сохранить"))
        self.label_57.setText(_translate("MainWindow", "Расчитанная информация:"))
        self.numberKp1_Surf.setText(_translate("MainWindow", "None..."))
        self.label_52.setText(_translate("MainWindow", "Количество особых точек\n"
"на изображении объекта"))
        self.numberKp2_Surf.setText(_translate("MainWindow", "None..."))
        self.label_53.setText(_translate("MainWindow", "Количество особых точек\n"
"на изображении сцены"))
        self.goodMatchesSurf.setText(_translate("MainWindow", "None..."))
        self.label_63.setText(_translate("MainWindow", ":Количество совпадений"))
        self.numberGood_Surf.setText(_translate("MainWindow", "None..."))
        self.label_54.setText(_translate("MainWindow", "Процент схожести изображений\n"
"при сравнении"))
        self.btnMesureImg.setText(_translate("MainWindow", "Сравнить\n"
"изображения"))
        self.btnShowRecognitionSift.setText(_translate("MainWindow", "Вывести\n"
"изображения"))
        self.label_12.setText(_translate("MainWindow", "Примечание:\n"
"сначала идет сравнение\n"
"затем индикация"))
        self.btnSaveSift.setText(_translate("MainWindow", "Сохранить"))
        self.label_14.setText(_translate("MainWindow", "Коэффициент сравнения\n"
"дескрипторов\n"
"от 0 до 1"))
        self.numberKp1.setText(_translate("MainWindow", "None..."))
        self.label_11.setText(_translate("MainWindow", "Количество особых точек\n"
"на изображении объекта"))
        self.numberKp2.setText(_translate("MainWindow", "None..."))
        self.label_48.setText(_translate("MainWindow", "Количество особых точек\n"
"на изображении сцены"))
        self.numberGood.setText(_translate("MainWindow", "None..."))
        self.label_10.setText(_translate("MainWindow", "Процент схожести изображений\n"
"при сравнении"))
        self.goodMatchesSift.setText(_translate("MainWindow", "None..."))
        self.label_64.setText(_translate("MainWindow", ":Количество совпадений"))
        self.label_58.setText(_translate("MainWindow", "Корреляционный алгоритм:"))
        self.btnMessureCorrelation.setText(_translate("MainWindow", "Сравнить\n"
"изображения"))
        self.btnShowRecognitionCorrelation.setText(_translate("MainWindow", "Вывести\n"
"изображение\n"
"корреляции и\n"
"результат"))
        self.label_59.setText(_translate("MainWindow", "Примечание:\n"
"сначала идет сравнение\n"
"затем индикация"))
        self.label_61.setText(_translate("MainWindow", "Тип корреляции\n"
"  1 - глобальный минимум квадрата отклонения\n"
": 2 - глобальный максимум взаимной коррреляции\n"
"  5 - глобальный максимум коэффициента корреляции "))
        self.label_62.setText(_translate("MainWindow", "Расчитанная информация:"))
        self.correlationKf.setText(_translate("MainWindow", "None..."))
        self.label_60.setText(_translate("MainWindow", ": Коэффициент корреляции"))
